name: platform_plus
description: Platform Plus is a package for easily figuring out information about the platform your code is running on
version: 4.5.0
homepage: https://github.com/Rexios80/platform_plus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  browser_detector: ^2.0.0
  device_info_plus: ^10.0.1
  package_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^6.0.1
